---
name: Tag

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Tag
        run: |
          if ! [[ ${{ github.event.inputs.tag }} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "tag needs to be x.y.z, e.g. 1.2.3"
            exit 1
          fi
          git tag v${{ github.event.inputs.tag }}
          git push origin v${{ github.event.inputs.tag }}
